version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
  redis:
    image: redis:alpine
    restart: always
  backend:
    build: .
    volumes:
      - ./backend/:/web_app
    env_file:
      - .env
    environment:
      #FLASK_APP: APP
      FLASK_ENV: development
      REDIS_URL: redis://redis
      PORT: 5000
      DATABASE_URL: postgresql://postgres@db/postgres
    command: ./wait-for-pg.sh db flask run --host=0.0.0.0
    #command: apachectl -D FOREGROUND
    ports:
      - "5000:5000"
    depends_on: 
      - db
  frontend:
    build: frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    command: npm start
